import prisma from "@/lib/prisma";
import { addMonths, addWeeks, addDays } from "date-fns";

export async function processRecurringTasks() {
  let createdCount = 0;

  try {
    const now = new Date();

    // Find all active schedules whose nextRunAt is in the past or now
    const schedules = await prisma.recurringTaskSchedule.findMany({
      where: {
        isActive: true,
        nextRunAt: {
          lte: now,
        },
      },
      include: {
        taskMaster: {
          select: { name: true, defaultDuration: true }
        }
      }
    });

    for (const schedule of schedules) {
      // Calculate the next run date based on frequency
      let nextRun = new Date(schedule.nextRunAt);
      if (schedule.frequency === "MONTHLY") {
        nextRun = addMonths(nextRun, 1);
      } else if (schedule.frequency === "WEEKLY") {
        nextRun = addWeeks(nextRun, 1);
      } else if (schedule.frequency === "DAILY") {
        nextRun = addDays(nextRun, 1);
      } else {
        // Fallback
        nextRun = addDays(nextRun, 1);
      }

      // Ensure nextRun is in the future in case it was missed multiple times
      while (nextRun <= now) {
        if (schedule.frequency === "MONTHLY") nextRun = addMonths(nextRun, 1);
        else if (schedule.frequency === "WEEKLY") nextRun = addWeeks(nextRun, 1);
        else nextRun = addDays(nextRun, 1);
      }

      // Determine task title
      const runDateStr = new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
      const taskMasterName = schedule.taskMaster?.name || "Recurring Task";
      const taskName = `${taskMasterName} - ${runDateStr}`;

      // Calculate planned start and end based on template duration
      const plannedStart = now;
      let plannedEnd = null;
      const duration = schedule.taskMaster?.defaultDuration || null;
      if (duration !== null) {
        plannedEnd = addDays(plannedStart, duration);
      }

      // Create the task in a transaction along with updating the schedule
      await prisma.$transaction(async (tx) => {
        // 1. Create the task
        await tx.task.create({
          data: {
            tenantId: schedule.tenantId,
            name: taskName,
            description: `Autogenerated recurring task: ${taskName}`,
            projectId: schedule.projectId,
            assignedToId: schedule.assignedToId,
            departmentId: schedule.departmentId,
            taskMasterId: schedule.taskMasterId,
            status: "TODO",
            priority: "MEDIUM",
            lifecycleStatus: "PROPOSED", // Default as per user request
            proposedById: schedule.assignedToId, // Using assignee as proposer for now
            proposedAt: new Date(),
            plannedStart: plannedStart,
            plannedEnd: plannedEnd,
            plannedDuration: duration,
          },
        });

        // 2. Notify the assigned user if there is one
        if (schedule.assignedToId) {
          await tx.notification.create({
            data: {
              tenantId: schedule.tenantId,
              userId: schedule.assignedToId,
              title: "Recurring Task Auto-Assigned — Awaiting Review",
              message: `The recurring task "${taskName}" was automatically assigned to you. Please review and accept or negotiate.`,
              type: "INFO",
              link: `/dashboard/projects/${schedule.projectId}`,
            },
          });
        }

        // 3. Update the schedule
        await tx.recurringTaskSchedule.update({
          where: { id: schedule.id },
          data: {
            lastRunAt: now,
            nextRunAt: nextRun,
          },
        });
      });

      createdCount++;
    }
  } catch (error) {
    console.error("[processRecurringTasks] Error processing recurring tasks:", error);
  }

  return createdCount;
}
